# Generated by Django 4.1.5 on 2026-04-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='dependence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='social_life',
            field=models.IntegerField(default=0),
        ),
    ]
