# Generated by Django 4.1.5 on 2026-04-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_alter_character_dependence_alter_character_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='count_for_question',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
