# Generated by Django 4.1.5 on 2026-04-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.AddField(
            model_name='decision',
            name='minimal_value_for_dependence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='decision',
            name='minimal_value_for_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='decision',
            name='minimal_value_for_social_life',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='decision',
            name='dependence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='decision',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='decision',
            name='social_life',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_index',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_title',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
