# Generated by Django 4.1.5 on 2026-04-26 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['index'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.RenameField(
            model_name='decision',
            old_name='decision_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_index',
            new_name='index',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_title',
            new_name='title',
        ),
    ]
