# Generated by Django 4.1.5 on 2026-04-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
