# Generated by Django 4.1.5 on 2026-04-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_decision_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('social_life', models.IntegerField(blank=True, null=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('dependence', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ending',
                'verbose_name_plural': 'Endings',
            },
        ),
    ]
