# Generated by Django 4.1.5 on 2026-04-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_endings'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='test_field',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
