# Generated by Django 4.1.5 on 2026-04-28 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_decision_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decision',
            name='test_field',
        ),
    ]
