# Generated by Django 4.1.5 on 2026-04-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_remove_decision_test_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
